version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: geracao_caldeira_db
    environment:
      POSTGRES_DB: geracao_caldeira_banco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha_banco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geracao_caldeira_network

  backend:
    build: ./back
    container_name: geracao_caldeira_backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=geracao_caldeira_banco
      - DB_USER=postgres
      - DB_PASS=sua_senha_banco
      - JWT_SECRET=ia-e-dadosxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=http://localhost:3000
      - OPENROUTER_API_KEY=sk-or-v1-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    depends_on:
      - db
    networks:
      - geracao_caldeira_network
    restart: unless-stopped

  frontend:
    build: ./front
    container_name: geracao_caldeira_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - geracao_caldeira_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  geracao_caldeira_network:
    driver: bridge
